/* AUTO-GENERATED by build.js — tag name to permalink slug. */
var TAG_SLUGS = {
  "כללי": "tag-rh2n2",
  "מאחורי הקלעים": "tag-q18gu4",
  "פיתוח": "tag-nslto7",
  "iOS": "ios",
  "מוצר": "tag-riunt",
  "SEO": "seo",
  "ווב": "tag-vrxt"
};
